spring.application.name=medisolution
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


#Update crea tablas si no existen o las modifica si se agregan campos
spring.jpa.hibernate.ddl-auto=update

# Para ver en consola lo que spring hace con sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true