package com.quiceno.medisolution.enums;

public enum Areas {
    CIRUGIA_GENERAL, ORTOPEDIA, TRAUMATOLOGIA, CIRUGIA_ALTA_COMPLEJIDAD, UROLOGIA, OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA, CIRUGIA_PEDIATRICA, CIRUGIA_PLASTICA
}
